### ISSUE TITLE
deterministic output

### ISSUE THREAD

**Issue by jcaplan** [hbmartin/graphviz2drawio#10]
Given an input, the output should be the same every time. This improves testability. Currently at least node orders are variable.

**Comment by hbmartin** [comment]
@jcaplan what's happening here is that nodes and edges are stored as `dict`s. Dict ordering is guaranteed in 3.6 (https://docs.python.org/3.6/whatsnew/3.6.html#new-dict-implementation) but is not in previous versions. It would require significant implementation changes to preserve order in the previous version which I think is unnecessary.
So I think in terms of testing we either only test on 3.6+ or make the tests flexible enough to not require element ordering. I prefer the latter since testing on 3.4 has already had positive effects :)

**Comment by jcaplan** [comment]
This is in graphviz2drawio or elsewhere? Shouldn't be too hard to change to OrderedDict if it's only in this project
https://docs.python.org/3/library/collections.html#collections.OrderedDict

**Comment by hbmartin** [comment]
Will close this once edges are ordered
