### ISSUE TITLE
Support for compound=true

### ISSUE THREAD

**Issue by mediapunk** [hbmartin/graphviz2drawio#32]
The DOT guide (https://www.graphviz.org/pdf/dotguide.pdf) gives an example of a "compound" digraph, which renders with edges between two clusters and edges between nodes and clusters:
```
digraph G {
  compound=true;
  subgraph cluster0 {
    a -> b;
    a -> c;
    b -> d;
    c -> d;
  }
  subgraph cluster1 {
    e -> g;
    e -> f;
  }
  b -> f [lhead=cluster1];
  d -> e;
  c -> g [ltail=cluster0,lhead=cluster1];
  c -> e [ltail=cluster0];
  d -> h;
}
```
![The DOT Guide rendering](https://user-images.githubusercontent.com/731931/76585809-f3727480-64a4-11ea-95ad-bb7ba87278c8.png)

When I convert this with graphviz2drawio, all the cluster information seems to get lost, and all the internal nodes are just connected together. Is there a way to get the conversion to keep the compound subgraph information? Or are you possibly planning on adding support for that?

The graphviz2drawio conversion:

![Screen Shot 2020-03-12 at 9 05 48 PM](https://user-images.githubusercontent.com/731931/76586087-7267ad00-64a5-11ea-8420-781187ec7fe7.png)

**Comment by hbmartin** [comment]
This is fixed in the upcoming 0.3 release and automated testing has been added for that file.
Feel free to reopen or create a new issue if that release does not work as you expect.
Thanks for the report!

<img width="247" alt="Screenshot 2024-07-02 at 4 09 55 PM" src="https://github.com/hbmartin/graphviz2drawio/assets/745166/4b601cf1-30ac-4d8c-805c-d5ad02c6909c">
