### ISSUE TITLE
node shapes should be respected

### ISSUE THREAD

**Issue by jcaplan** [hbmartin/graphviz2drawio#4]
Basic shapes should be supported (box, egg, hexagon, octagon, parallelogram). Conversion to rectangles is not ideal as shapes are usually basic vocabulary in many graph notations e.g. https://areyoumodeling.files.wordpress.com/2015/02/gsn.png

**Comment by hbmartin** [comment]
Thanks a lot for this report. Working on this and the other issues and will have an update out in a few days.

**Comment by jcaplan** [comment]
Awesome! I’ve got a ton of generated dot files that need to start being edited manually and not everybody’s a programmer. draw.io would be ideal compared to svg editors. This project is a life saver! Much appreciated 😁

**Comment by hbmartin** [comment]
Will have a commit up for this issue later today

**Comment by hbmartin** [comment]
@jcaplan fixed in https://github.com/hbmartin/graphviz2drawio/commit/13490c60c3e4c87cc08f9238c7e8f12237b4ff75
Check out the results!
<img width="422" alt="screenshot 2018-09-05 15 05 11" src="https://user-images.githubusercontent.com/745166/45123970-70d56000-b11d-11e8-866b-eb8eadca38d7.png">

I opened a new issue for the edge positioning: https://github.com/hbmartin/graphviz2drawio/issues/7
